pranaOS/pranaOS

kernel/archs/x86/CPUID.h

hi sir i have adde some structure for packed

packed structure added

---

kernel/archs/x86/CPUID.h

hi sir i have fixed some issues in the code please review it

cpu id headers

---

base/ByteReader.h

hey hi @krishpranav i have added ByteReader headers check it out!.

ByteReader headers

---

base/ExtraMathConstants.h

things added: non standard math constants for math
what it does: it is a standard constant file for math functions

ExtraMathConstants headers

---

userland/utilities/echo.cpp

Created echo.cpp

---

sysroot/home/anon/Source/js/typeof.js

typeof js typedef 

---

kernel/bus/usb/UHCIController.h

hi @krishpranav I have added uhcicontroller headers check it out

UHCIController headers

---

meta/lint-ports.py
meta/lint-shell-scripts.sh

hi krishpranav I have added lint functions for testing so check it out

lint functions

---

meta/Lagom/Fuzzers/FuzzBMPLoader.cpp
meta/Lagom/Fuzzers/FuzzCyrillicDecoder.cpp
meta/Lagom/Fuzzers/FuzzDeflateCompression.cpp
meta/Lagom/Fuzzers/FuzzDeflateDecompression.cpp
meta/Lagom/Fuzzers/FuzzELF.cpp
meta/Lagom/Fuzzers/FuzzFlacLoader.cpp
meta/Lagom/Fuzzers/FuzzGIFLoader.cpp

hi @krishpranav I have added:
Fuzzing functions for
BmpLoader
CyrillicDecoder
DeflateCompression
DeflateDecompression
ELF
FlacLoader
GIFLoder

fuzz values

---

meta/Lagom/Fuzzers/FuzzPGMLoader.cpp
meta/Lagom/Fuzzers/FuzzPNGLoader.cpp
meta/Lagom/Fuzzers/FuzzPPMLoader.cpp
meta/Lagom/Fuzzers/FuzzQuotedPrintableParser.cpp

Things added:
pgm loader
png loader
ppm loader
quoted printable parser

Fuzzing functions

---

meta/Lagom/Fuzzers/FuzzilliJs.cpp

Fuzz illijs

---

kernel/devices/MemoryDevice.cpp
kernel/devices/MemoryDevice.h

Things I've added:
MemoryDevice.cpp
MemoryDevice.h
Features I've Added:
- MemoryDevice.cpp
```sh
Phyiscal Memory Mapping Function
did seek
```

MemoryDevice

---

kernel/filesystem/AnonymousFile.cpp
kernel/filesystem/AnonymousFile.h
kernel/filesystem/BlockBasedFileSystem.h

hey krish I've added anonymous file content, block basedfilesystem check it out!!

AnonymousFile, BlockBasedFileSystem

---

kernel/storage/IDEChannel.cpp
kernel/storage/IDEController.cpp
kernel/storage/IDEController.h

some storage channels, controllers added

storage IDE

---

kernel/include/platform/aarch32/settings.h

hi @krishpranav I have added Pmm settings require for arm

Pmm Settings headers

---

kernel/include/platform/aarch32/tasking/trapframe.h

hi @krishpranav I've added some trap frame headers

trapframe headers

---

kernel/include/platform/generic/vmm/pde.h
kernel/include/platform/generic/vmm/pf_types.h
kernel/include/platform/generic/vmm/pte.h

hi @krishpranav I've added some generic kernel header file which will be useful for the whole project check it out!!!

some headers require for generic kernel

---

kernel/include/platform/x86/gdt.h

hi @krishpranav I've added gdt headers check it out!!

gdt headers

---

userland/libraries/libc/byteswap.h
userland/libraries/libc/crt0.cpp
userland/libraries/libc/crt0_shared.cpp

some headers that added in libc require for pranaOS

libc: byteswap, crt0

---

libs/libabi/BUILD.gn
libs/libabi/system.h

hi @krishpranav I have added system funs 
added system-status, system info(kernel name, release, build, machine name), #defined systeminfofieldsize(65)
author: evilbat831
https://github.com/evilbat831

libabi: system funs

---

libs/libutils/tags.h

hi @krishpranav check the thing I just added some auto constexpr for enum values
first pull request of me @samvirg-git 
authors: @krishpranav, @samvirg-git

tags header

---

libs/libobjc/include/libobjc/module.h
userland/utilities/edit/file.h
userland/utilities/edit/lifetime.h
userland/utilities/edit/menu.h
userland/utilities/edit/viewer.h

hey @krishpranav I have changed #ifndef -> #pragma once in some files I just cloned this repo and I builded pranaOS for make sure that pranaOS is not crashing it is going well and I feel some what is speed when I change from #ifndef -> #pragma once 
so I recommend you to change from #ifndef -> #pragma once this will be a biggest plus point for the next version leopard version
thanks
fix: #ifndef -> #pragma once
author: @krishpranav
co-author: @evilbat831

fix: #ifndef -> #pragma once

---

libs/libc/include/sys/_types/_devs.h
libs/libc/include/sys/_types/_ints.h
libs/libc/include/sys/_types/_va_list.h

hello sir I just saw the issue:
[issue 99](https://github.com/pranaOS/pranaOS/issues/99)
I have just changed from #ifndef -> #pragma once in some sys files under libc 
I hope you like the work that I have made :) 
Regards,
@ASPECThalalexmine

fixed: #ifndef -> #pragma once 

---

kernel/include/libkern/c_attrs.h
kernel/include/libkern/libkern.h
kernel/include/libkern/types.h
libs/libc/include/stdint.h
libs/libc/include/stdlib.h

fix: #ifndef -> #pragma once
issue: #99
author: @krishpranav
co-author: @NukeWilliams

convert: #ifndef -> #pragma once in some headers

---

CMakeLists.txt

gn -> cmake
added main cmake file for building this whole project
fixme: add your cmake current list dir here
issue: #105

fixme: main CMakeList 

---

docs/codingstyle.md

Made the codingstyle.md look better

---

run/fuse.py

fuse code update

---

ak/convert.cpp
ak/convert.h
ak/memoperator.cpp
ak/memoperator.h
ak/print.cpp
ak/print.h
ak/random.h
ak/string.cpp
ak/string.h
bootloader/stage2/math/math.cpp
external/eclib/vector.h

hey @krishpranav i have updated the include paths
last updated: Thu 6 Jan
changes by: @NukeWilliams 
author: @krishpranav

[libs + ak] updated the include paths

---

kernel/core/memory.h

Hello ✋ so i am @biggboy021 new to contributing to open-source projects i have found your // TODO block so i started thinking to help you 
hope this pull request will be helpfull for your project :) 
author: @krishpranav 
co-author: @biggboy021

Kernel: core cpu 

---

kernel/input/keyboard.h
kernel/input/keyboardmanager.h

hey @krishpranav i have added keyboard support for pranaOS kernel[supports ps2 + usb keyboard]
hope you like it and this is just a header file i didnt add the main func

Kernel: keyboard support

---

kernel/drivers/usb/defs.h
kernel/drivers/usb/usbdriver.h

hey @krishpranav i have added usb device filesystem + usbdriver header

Kernel: usb driver

---

userland/libraries/libc/datetime.cpp

hey i have added datetime main function need to add some func for convertion

Libc: datetime header 

---

grub.cfg
makefile.config

hey krish i have added makefile + grub config flie

Makefile + Grub Config Fille

---

kernel/usb/usbcontroller.h
kernel/usb/usbdevice.h

こんにちは私はUSBデバイスとコントローラーにいくつかの機能を追加しました
あなたがそれを好きになることを願っています

Kernel: [usb] usbcontroller + usbdevice

---

kernel/drivers/integrated/ps2mouse.h

hey @krishpranav i have added ps2mouse in a driver 
you can use this header to create ps2 mouse functions 
regards
- lucas

kernel: drivers ps2mousedriver header

---

kernel/cpu/vm.h

こんにちは私はvmヘッダーを更新しましたあなたが私のプルリクエストを気に入ってくれることを願っています

kernel: cpu vm header

---

userland/libraries/libc/stdint.h

こんにちは私はstdintヘッダーを追加しました、あなたはそれを多くのソースファイルに含めましたが、私はstdintを見つけることができませんでした

libc: stdint header

---

userland/libraries/libc/dirent.h

こんにちは私はdirヘッダーを更新しました。私が行った変更を確認してください。

Libc: dirent header 

---

mods/concept.h

Hey, krish i am a pretty newbie to the github and all those things recently i was exploring some ethical hacking stuffs, and i found your backdoorcreator thing and i was exploring your profile and found this operating system that you built using c++ for mobile, watch and bare-metal(x86 and arm). this looks pretty good i wrote some concepts which helps in finding int or float this concept would help you in building other parts of the os.
i would love to build/add more features for your system.
Thanks
Regards
- Patrick.

Mods: Concept 
